In [1]:
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

In [2]:
def read_and_convert_to_binary(filepath, threshold = 0.3, coef=0.4):
    """
    Requires numpy and Image from PIL
    """
    image = Image.open(filepath)

    data = np.asarray(image)
    data = 0.2989 * data[:,:,0] + 0.5870 * data[:,:,1] + 0.1140 * data[:,:,2]
    data = data / 255
    data = 1 - data

    rowSums = data.sum(axis=1)
    colSums = data.sum(axis=0)

    data[rowSums <= 4, :] = 0
    data[:, colSums <= 6] = 0
    
    data = data > threshold

    return data  

In [3]:
image = read_and_convert_to_binary("Skany profili/Profil 002.1.jpg")

In [4]:
data = image

In [5]:
rowSums, colSums = data.sum(axis=1), data.sum(axis=0)

In [23]:
rowSums[:300]

array([271, 294, 294, 294, 294, 294, 294, 294, 294, 294, 294, 294, 294,
       294, 294, 294, 294, 294, 294, 294, 294, 294, 295, 294, 295, 295,
       295, 295, 295, 295, 295, 295, 295, 295, 295, 295, 295, 295, 295,
       295, 295, 295, 295, 295, 295, 295, 295, 295, 295, 295, 296, 295,
       296, 296, 296, 296, 296, 296, 296, 296, 296, 296, 296, 287, 279,
       278, 259, 245, 229, 217, 213, 207, 204, 210, 219, 227, 228, 232,
       238, 236, 240, 240, 240, 239, 243, 244, 245, 248, 247, 248, 246,
       246, 244, 244, 246, 246, 245, 246, 244, 242, 236, 235, 234, 235,
       236, 237, 232, 226, 223, 214, 199, 202, 205, 215, 223, 235, 248,
       273, 287, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297,
       297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297,
       297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297,
       297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297,
       297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 29

In [39]:
rowDiffs = np.diff(rowSums[:250])
colDiffs = np.diff(colSums)


In [40]:
rowDiffs

array([  23,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
         -1,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    1,   -1,    1,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   -9,   -8,   -1,  -19,
        -14,  -16,  -12,   -4,   -6,   -3,    6,    9,    8,    1,    4,
          6,   -2,    4,    0,    0,   -1,    4,    1,    1,    3,   -1,
          1,   -2,    0,   -2,    0,    2,    0,   -1,    1,   -2,   -2,
         -6,   -1,   -1,    1,    1,    1,   -5,   -6,   -3,   -9,  -15,
          3,    3,   10,    8,   12,   13,   25,   14,   10,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [41]:
rowDiffs = (rowDiffs < -0.1*np.max(np.abs(rowDiffs[:data.shape[0]//2]))).astype(np.int8)
colDiffs = (colDiffs < -0.1*np.max(np.abs(colDiffs[:data.shape[1]//2]))).astype(np.int8)

In [43]:
np.where(rowDiffs)

(array([ 65,  66,  67,  68, 109, 212, 213, 214], dtype=int64),)

In [6]:
np.argmax([False, False, True, False])

2